backend:
  name: github
  repo: j3nsykes/j3nsykes.github.io
  branch: master
  site_domain: silly-einstein-85813b.netlify.com

media_folder: "images/uploads"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

- name: "Robot"
  label: "robots"
  files: 
    - label: "robotResidency"
      name: "robotResidency"
      file: "RobotsInResidence/index.html"
      fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "text"}

- name: "Home"
  label: "home"
  files: 
    - label: "Homepage"
      name: "homepage"
      file: "index.html"
      fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "text"}
